development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: expense_dev
  username: root
  password: root

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: expense_test
  username: root
  password: root

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  username: <%=ENV['OPENSHIFT_MYSQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_MYSQL_DB_PASSWORD']%>
  # socket:   <%=ENV['OPENSHIFT_MYSQL_DB_SOCKET']%>
  host:     <%=ENV['OPENSHIFT_MYSQL_DB_HOST']%>
  port:     <%=ENV['OPENSHIFT_MYSQL_DB_PORT']%>
